import {
  ArrowDown,
  ArrowDownToLine,
  ArrowLeftToLine,
  ArrowRightToLine,
  ArrowUpToLine,
  Bold,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  Code,
  Columns2,
  Columns3,
  ExternalLink,
  Eye,
  Grid2x2Check,
  Grid2x2X,
  GripVertical,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  Italic,
  Link,
  PencilRuler,
  PilcrowRight,
  Plus,
  Quote,
  RefreshCcw,
  Search,
  Strikethrough,
  Subscript,
  Superscript,
  Text,
  Trash,
  Underline,
  Unlink,
  X,
} from "lucide-react";

const Icons = {
  chevronsUpDown: (props: any) => <ChevronsUpDown {...props} />,
  check: (props: any) => <Check {...props} />,
  close: (props: any) => <X {...props} />,
  delete: (props: any) => <Trash {...props} />,
  doubleColumn: (props: any) => <Columns2 {...props} />,
  threeColumn: (props: any) => <Columns3 {...props} />,
  search: (props: any) => <Search {...props} />,
  more: (props: any) => <ChevronRight {...props} />,
  refresh: (props: any) => <RefreshCcw {...props} />,
  dragHandle: (props: any) => <GripVertical {...props} />,
  chevronRight: (props: any) => <ChevronRight {...props} />,
  bold: (props: any) => <Bold {...props} />,
  italic: (props: any) => <Italic {...props} />,
  underline: (props: any) => <Underline {...props} />,
  strikethrough: (props: any) => <Strikethrough {...props} />,
  code: (props: any) => <Code {...props} />,
  paragraph: (props: any) => <PilcrowRight {...props} />,
  h1: (props: any) => <Heading1 {...props} />,
  h2: (props: any) => <Heading2 {...props} />,
  h3: (props: any) => <Heading3 {...props} />,
  h4: (props: any) => <Heading4 {...props} />,
  h5: (props: any) => <Heading5 {...props} />,
  h6: (props: any) => <Heading6 {...props} />,
  blockquote: (props: any) => <Quote {...props} />,
  add: (props: any) => <Plus {...props} />,
  link: (props: any) => <Link {...props} />,
  text: (props: any) => <Text {...props} />,
  externalLink: (props: any) => <ExternalLink {...props} />,
  unlink: (props: any) => <Unlink {...props} />,
  editing: (props: any) => <PencilRuler {...props} />,
  viewing: (props: any) => <Eye {...props} />,
  superscript: (props: any) => <Superscript {...props} />,
  subscript: (props: any) => <Subscript {...props} />,

  borderBottom: (props: any) => <ArrowDownToLine {...props} />,
  borderTop: (props: any) => <ArrowUpToLine {...props} />,
  borderLeft: (props: any) => <ArrowLeftToLine {...props} />,
  borderRight: (props: any) => <ArrowRightToLine {...props} />,
  borderNone: (props: any) => <Grid2x2X {...props} />,
  borderAll: (props: any) => <Grid2x2Check {...props} />,
  chevronDown: (props: any) => <ChevronDown {...props} />,
  arrowDown: (props: any) => <ArrowDown {...props} />,
};

export default Icons;
